Add Version information to application
polychatproject/polychat-appservice pull request #36
Opened 2024-05-20 07:46 UTC by lukeelten

Solve #34 

This PR adds version information about the application to the docker image and the application.

Example:
```
VERSION_NAME=td/versioning
VERSION_HASH=a3325084999a1b46fe56d3bad71775fa23247be5
VERSION_CREATOR=lukeelten
```

2024-07-13 01:06 UTC, jaller94 commented
![Screenshot 2024-07-13 at 02-58-29 Polychat](https://github.com/user-attachments/assets/695ed848-c846-43fb-994d-3ea5f56a836b)

or write "version" in any Control Room.

2024-07-13 01:35 UTC, jaller94 commented
@lukeelten Im Frontend docker build scheinen die Variablen "VERSION_HASH" und "VERSION_NAME" noch nicht korrekt gesetzt.

https://github.com/polychatproject/polychat-appservice/actions/runs/9916221627/job/27398213115?pr=36#step:6:352

![2024-07-13_03-35](https://github.com/user-attachments/assets/e2bc051e-1e3b-401f-813e-aa9930da2716)

2024-07-13 01:37 UTC, jaller94 requested changes
Docker build schlägt fehl, weil die Env Vars scheinbar noch fehlen.
Der Code sieht eigentlich bereits gut aus.

2024-08-26 20:31 UTC, lukeelten commented
Sollte jetzt klappen

2024-08-28 11:53 UTC, merged